"""
This is the people module and supports all the ReST actions for the
PEOPLE collection
"""
import datetime
import logging
# System modules
import pickle
import random
import base64

# 3rd party modules
from flask import (
    abort
)

import ibd_predictor

# Just in case we get a crash during the demo..
defaultFileData = """k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_uniformis	29.68076
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Ruminococcaceae	g__Faecalibacterium	s__Faecalibacterium_prausnitzii	14.43791
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_thetaiotaomicron	7.45138
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Porphyromonadaceae	g__Parabacteroides	s__Parabacteroides_merdae	7.33468
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_vulgatus	7.01313
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_ovatus	5.49937
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Porphyromonadaceae	g__Parabacteroides	s__Parabacteroides_unclassified	3.83957
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Eubacteriaceae	g__Eubacterium	s__Eubacterium_eligens	3.11266
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_caccae	2.85939
k__Bacteria	p__Proteobacteria	c__Betaproteobacteria	o__Burkholderiales	f__Sutterellaceae	g__Sutterella	s__Sutterella_wadsworthensis	2.65265
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_massiliensis	2.49677
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Eubacteriaceae	g__Eubacterium	s__Eubacterium_rectale	2.4862
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_dorei	2.25618
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Roseburia	s__Roseburia_intestinalis	1.49007
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Oscillospiraceae	g__Oscillibacter	s__Oscillibacter_unclassified	1.38646
k__Bacteria	p__Firmicutes	c__Negativicutes	o__Selenomonadales	f__Veillonellaceae	g__Dialister	s__Dialister_invisus	1.38289
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Eubacteriaceae	g__Eubacterium	s__Eubacterium_ventriosum	0.75244
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_salyersiae	0.65776
k__Bacteria	p__Firmicutes	c__Negativicutes	o__Selenomonadales	f__Veillonellaceae	g__Veillonella	s__Veillonella_atypica	0.44186
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_leptum	0.32199
k__Bacteria	p__Actinobacteria	c__Actinobacteria	o__Bifidobacteriales	f__Bifidobacteriaceae	g__Bifidobacterium	s__Bifidobacterium_adolescentis	0.27465
k__Bacteria	p__Actinobacteria	c__Actinobacteria	o__Bifidobacteriales	f__Bifidobacteriaceae	g__Bifidobacterium	s__Bifidobacterium_longum	0.26293
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Prevotellaceae	g__Prevotella	s__Prevotella_copri	0.25257
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiales_noname	g__Flavonifractor	s__Flavonifractor_plautii	0.23074
k__Bacteria	p__Firmicutes	c__Negativicutes	o__Selenomonadales	f__Veillonellaceae	g__Veillonella	s__Veillonella_parvula	0.14844
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Lachnospiraceae_noname	s__Lachnospiraceae_bacterium_7_1_58FAA	0.11388
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Dorea	s__Dorea_longicatena	0.10816
k__Bacteria	p__Proteobacteria	c__Gammaproteobacteria	o__Pasteurellales	f__Pasteurellaceae	g__Haemophilus	s__Haemophilus_parainfluenzae	0.10543
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Roseburia	s__Roseburia_inulinivorans	0.10142
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Ruminococcaceae	g__Subdoligranulum	s__Subdoligranulum_unclassified	0.09462
k__Bacteria	p__Proteobacteria	c__Betaproteobacteria	o__Burkholderiales	f__Burkholderiales_noname	g__Burkholderiales_noname	s__Burkholderiales_bacterium_1_1_47	0.08579
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_symbiosum	0.08466
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_xylanisolvens	0.068
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Coprococcus	s__Coprococcus_comes	0.06564
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_bolteae	0.04215
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridiaceae_noname	s__Clostridiaceae_bacterium_JC118	0.041
k__Bacteria	p__Proteobacteria	c__Betaproteobacteria	o__Burkholderiales	f__Sutterellaceae	g__Parasutterella	s__Parasutterella_excrementihominis	0.03671
k__Bacteria	p__Actinobacteria	c__Actinobacteria	o__Bifidobacteriales	f__Bifidobacteriaceae	g__Bifidobacterium	s__Bifidobacterium_bifidum	0.03655
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Blautia	s__Ruminococcus_torques	0.0341
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_hathewayi	0.03143
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Lachnospiraceae_noname	s__Lachnospiraceae_bacterium_3_1_46FAA	0.0283
k__Bacteria	p__Actinobacteria	c__Actinobacteria	o__Coriobacteriales	f__Coriobacteriaceae	g__Collinsella	s__Collinsella_aerofaciens	0.02544
k__Bacteria	p__Actinobacteria	c__Actinobacteria	o__Bifidobacteriales	f__Bifidobacteriaceae	g__Bifidobacterium	s__Bifidobacterium_breve	0.02495
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Peptostreptococcaceae	g__Peptostreptococcaceae_noname	s__Clostridium_bartlettii	0.02372
k__Bacteria	p__Firmicutes	c__Negativicutes	o__Selenomonadales	f__Veillonellaceae	g__Veillonella	s__Veillonella_dispar	0.02282
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Roseburia	s__Roseburia_hominis	0.01994
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Peptostreptococcaceae	g__Peptostreptococcaceae_noname	s__Peptostreptococcaceae_noname_unclassified	0.01862
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Dorea	s__Dorea_unclassified	0.01505
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiales_noname	g__Clostridiales_noname	s__Clostridiales_bacterium_1_7_47FAA	0.01282
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Bacteroidaceae	g__Bacteroides	s__Bacteroides_faecis	0.01278
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_asparagiforme	0.01205
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Dorea	s__Dorea_formicigenerans	0.00354
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Clostridiaceae	g__Clostridium	s__Clostridium_citroniae	0.00302
k__Bacteria	p__Firmicutes	c__Clostridia	o__Clostridiales	f__Lachnospiraceae	g__Blautia	s__Ruminococcus_gnavus	0.00264
k__Bacteria	p__Bacteroidetes	c__Bacteroidia	o__Bacteroidales	f__Porphyromonadaceae	g__Parabacteroides	s__Parabacteroides_distasonis	0.00133
"""

metaflanVector = """s__Bacteroides_uniformis
s__Bacteroides_thetaiotaomicron
s__Faecalibacterium_prausnitzii
s__Bacteroides_vulgatus
s__Bacteroides_caccae
s__Clostridium_clostridioforme
s__Roseburia_unclassified
s__Dialister_invisus
s__Ruminococcus_torques
s__Bacteroides_fragilis
s__Oscillibacter_unclassified
s__Ruminococcus_gnavus
s__Subdoligranulum_unclassified
s__C2likevirus_unclassified
s__Eubacterium_hallii
s__Clostridium_bolteae
s__Clostridiales_bacterium_1_7_47FAA
s__Ruminococcus_obeum
s__Clostridium_asparagiforme
s__Dorea_longicatena
s__Dorea_unclassified
s__Anaerotruncus_unclassified
s__Clostridium_leptum
s__Clostridium_symbiosum
s__Flavonifractor_plautii
s__Anaerotruncus_colihominis
s__Escherichia_coli
s__Clostridium_hathewayi
s__Bacteroides_dorei
s__Escherichia_unclassified
s__Clostridium_citroniae
s__Lachnospiraceae_bacterium_7_1_58FAA
s__Bacteroides_stercoris
s__Bifidobacterium_longum
s__Alistipes_putredinis
s__Roseburia_hominis
s__Eubacterium_siraeum
s__Parabacteroides_distasonis
s__Bacteroides_ovatus
s__Parabacteroides_merdae
s__Roseburia_inulinivorans
s__Lachnospiraceae_bacterium_5_1_63FAA
s__Erysipelotrichaceae_bacterium_5_2_54FAA
s__Lachnospiraceae_bacterium_1_4_56FAA
s__Bacteroides_cellulosilyticus
s__Bifidobacterium_adolescentis
s__Eggerthella_unclassified
s__Anaerostipes_hadrus
s__Bacteroidales_bacterium_ph8
s__Eubacterium_rectale
s__Lachnospiraceae_bacterium_3_1_46FAA
s__Eubacterium_eligens
s__Bacteroides_xylanisolvens
s__Eubacterium_sp_3_1_31
s__Alistipes_onderdonkii
s__Akkermansia_muciniphila
s__Haemophilus_parainfluenzae
s__Streptococcus_agalactiae
s__Veillonella_unclassified
s__Veillonella_parvula
s__Acidaminococcus_unclassified
s__Parabacteroides_johnsonii
s__Bacteroides_salyersiae
s__Veillonella_atypica
s__Lachnospiraceae_bacterium_8_1_57FAA
s__Roseburia_intestinalis
s__Megasphaera_micronuciformis
s__Prevotella_copri
s__Bacteroides_finegoldii
s__Alistipes_unclassified
s__Odoribacter_unclassified
s__Collinsella_tanakaei
s__Desulfovibrio_piger
s__Alistipes_finegoldii
s__Ruminococcus_lactaris
s__Alistipes_shahii
s__Lachnospiraceae_bacterium_5_1_57FAA
s__Bilophila_unclassified
s__Adlercreutzia_equolifaciens
s__Holdemania_filiformis
s__Bacteroides_faecis
s__Fusobacterium_ulcerans
s__Lachnospiraceae_bacterium_2_1_58FAA
s__Sutterella_wadsworthensis
s__Klebsiella_pneumoniae
s__Coprobacillus_unclassified
s__Erysipelotrichaceae_bacterium_6_1_45
s__Parabacteroides_unclassified
s__Holdemania_unclassified
s__Propionibacterium_acnes
s__Human_herpesvirus_1
s__Streptococcus_thermophilus
s__Lachnospiraceae_bacterium_3_1_57FAA_CT1
s__Clostridium_bartlettii
s__Gordonibacter_pamelaeae
s__Peptostreptococcaceae_noname_unclassified
s__Ruminococcaceae_bacterium_D16
s__Anaerofustis_stercorihominis
s__Clostridium_scindens
s__Granulicella_unclassified
s__Lachnospiraceae_bacterium_1_1_57FAA
s__Corynebacterium_matruchotii
s__Parasutterella_excrementihominis
s__Burkholderiales_bacterium_1_1_47
s__Clostridium_nexile
s__Collinsella_aerofaciens
s__Proteus_mirabilis
s__Barnesiella_intestinihominis
s__Paraprevotella_unclassified
s__Clostridium_ramosum
s__Blautia_producta
s__Lactococcus_phage_BM13
s__Bacteroides_sp_3_2_5
s__Klebsiella_unclassified
s__Ruminococcus_bromii
s__Odoribacter_splanchnicus
s__Alistipes_indistinctus
s__Coprococcus_comes
s__Bilophila_wadsworthia
s__Blautia_hydrogenotrophica
s__Dorea_formicigenerans
s__Anaerostipes_unclassified
s__Anaerostipes_caccae
s__Oscillibacter_sp_KLE_1728
s__Pseudoflavonifractor_capillosus
s__Clostridiaceae_bacterium_JC118
s__Epsilon15likevirus_unclassified
s__Mitsuokella_unclassified
s__Oscillibacter_sp_KLE_1745
s__Enterobacteriaceae_bacterium_9_2_54FAA
s__Hafnia_alvei
s__Prevotella_disiens
s__Bifidobacterium_animalis
s__Deinococcus_unclassified
s__Clostridium_sp_ATCC_BAA_442
s__Ruminococcus_sp_5_1_39BFAA
s__Subdoligranulum_sp_4_3_54A2FAA
s__Desulfovibrio_desulfuricans
s__Lachnospiraceae_bacterium_9_1_43BFAA
s__Eggerthella_lenta
s__Lachnospiraceae_bacterium_6_1_63FAA
s__Eubacterium_dolichum
s__Bacteroides_massiliensis
s__Streptococcus_salivarius
s__Bifidobacterium_catenulatum
s__Eubacterium_ventriosum
s__Streptococcus_parasanguinis
s__Coprococcus_catus
s__Acinetobacter_lwoffii
s__Kocuria_unclassified
s__Bacteroides_oleiciplenus
s__Bifidobacterium_bifidum
s__Butyrivibrio_unclassified
s__Bacteroides_nordii
s__Clostridium_sp_KLE_1755
s__Propionibacterium_granulosum
s__Micrococcus_luteus
s__Cellulophaga_unclassified
s__Bacteroides_gallinarum
s__Pseudomonas_aeruginosa
s__Pseudomonas_phage_JG024
s__Bacteroides_intestinalis
s__Porphyromonas_asaccharolytica
s__Methanobrevibacter_smithii
s__Eubacterium_ramulus
s__Methanobrevibacter_unclassified
s__Erysipelotrichaceae_bacterium_2_2_44A
s__Erysipelotrichaceae_bacterium_21_3
s__Porphyromonas_uenonis
s__Bacteroides_sp_9_1_42FAA
s__Clostridium_perfringens
s__Lactococcus_phage_P680
s__Lactobacillus_fermentum
s__Enterobacter_cloacae
s__Morganella_morganii
s__Rothia_mucilaginosa
s__Human_adenovirus_D
s__Providencia_unclassified
s__Shigella_flexneri
s__Streptococcus_vestibularis
s__Pseudomonas_unclassified
s__Lactococcus_lactis
s__Oxalobacter_formigenes
s__Alistipes_senegalensis
s__Ruminococcus_callidus
s__Staphylococcus_epidermidis
s__Enterococcus_faecium
s__Pantoea_unclassified
s__Bacteroides_plebeius
s__Paraprevotella_clara
s__Bacteroides_sp_2_1_22
s__Paraprevotella_xylaniphila
s__Bacteroides_eggerthii
s__Haemophilus_pittmaniae
s__Veillonella_dispar
s__Lactobacillus_delbrueckii
s__Propionibacterium_phage_PHL060L00
s__Ruminococcus_albus
s__Ruminococcus_flavefaciens
s__Lactobacillus_acidophilus
s__Burkholderia_unclassified
s__Pedobacter_unclassified
s__Bifidobacterium_breve
s__Coprobacter_fastidiosus
s__Subdoligranulum_variabile
s__Lactobacillus_sakei
s__Clostridium_innocuum
s__Alistipes_sp_AP11
s__Citrobacter_freundii
s__Klebsiella_oxytoca
s__Megasphaera_unclassified
s__Citrobacter_unclassified
s__Blautia_hansenii
s__Anaeroglobus_geminatus
s__Bifidobacterium_dentium
s__Eubacterium_biforme
s__Clostridium_difficile
s__Lactobacillus_sanfranciscensis
s__Bacillus_licheniformis
s__Fusobacterium_nucleatum
s__Clostridium_glycolicum
s__Neisseria_unclassified
s__Streptococcus_pseudopneumoniae
s__Prevotella_salivae
s__Lactobacillus_phage_Lc_Nu
s__Lactobacillus_salivarius
s__Avian_endogenous_retrovirus_EAV_HP
s__Lachnospiraceae_bacterium_4_1_37FAA
s__Streptococcus_gordonii
s__Fusobacterium_periodonticum
s__Jaagsiekte_sheep_retrovirus
s__Porcine_type_C_oncovirus
s__Megamonas_unclassified
s__Streptococcus_mitis_oralis_pneumoniae
s__Bacteroides_coprocola
s__Streptococcus_lutetiensis
s__Klebsiella_phage_KP36
s__Weissella_cibaria
s__Enterobacter_aerogenes
s__Parabacteroides_goldsteinii
s__Turicibacter_unclassified
s__Actinobacillus_unclassified
s__Butyricicoccus_pullicaecorum
s__Acidaminococcus_intestini
s__Coprococcus_sp_ART55_1
s__Alloscardovia_omnicolens
s__Streptococcus_infantis
s__Megamonas_funiformis
s__Parabacteroides_sp_20_3
s__Bifidobacterium_pseudocatenulatum
s__Turicibacter_sanguinis
s__Bacteroides_clarus
s__Streptococcus_sanguinis
s__Granulicatella_unclassified
s__Haemophilus_parahaemolyticus
s__Lactobacillus_amylovorus
s__Avian_myelocytomatosis_virus
s__Prevotella_stercorea
s__Megamonas_hypermegale
s__Megamonas_rupellensis
s__Streptococcus_intermedius
s__Streptococcus_australis
s__Alistipes_sp_HGB5
s__Human_adenovirus_F
s__Aggregatibacter_segnis
s__Aggregatibacter_unclassified
s__Bifidobacterium_pseudolongum
s__Alloprevotella_unclassified
s__Prevotella_bivia
s__Collinsella_unclassified
s__Dialister_micraerophilus
s__Collinsella_stercoris
s__Parvimonas_unclassified
s__Peptostreptococcus_stomatis
s__Enhydrobacter_aerosaccus
s__Paracoccus_unclassified
s__Parvimonas_micra
s__Peptostreptococcus_unclassified
s__Gemella_unclassified
s__Escherichia_albertii
s__Peptoniphilus_harei
s__Peptostreptococcus_anaerobius
s__Saccharomyces_cerevisiae
s__Mulikevirus_unclassified
s__Clostridium_sp_L2_50
s__Solobacterium_moorei
s__Nocardioides_unclassified
s__Murine_osteosarcoma_virus
s__Prevotella_buccae
s__Prevotella_denticola
s__Leuconostoc_lactis
s__Prevotella_dentalis
s__Prevotella_oris
s__Shuttleworthia_satelles
s__Eubacterium_infirmum
s__Prevotella_nigrescens
s__Bacteroides_sp_4_3_47FAA
s__Coprococcus_eutactus
s__Slackia_piriformis
s__Porphyromonas_somerae
s__Dysgonomonas_unclassified
s__Prevotella_buccalis
s__Streptococcus_phage_ALQ13_2
s__Eikenella_corrodens
s__Weissella_confusa
s__Erysipelotrichaceae_bacterium_3_1_53
s__Coprobacillus_sp_29_1
s__Bacteroides_sp_1_1_6
s__Candida_glabrata
s__Eremothecium_unclassified
s__Naumovozyma_unclassified
s__Raoultella_ornithinolytica
s__Dysgonomonas_gadei
s__Dysgonomonas_mossii
s__Veillonella_ratti
s__Lactococcus_phage_936_sensu_lato
s__Enterococcus_faecalis
s__Streptococcus_pasteurianus
s__Proteus_unclassified
s__Prevotella_melaninogenica
s__Granulicatella_adiacens
s__Propionibacterium_phage_PAD20
s__Enterococcus_hirae
s__Enterobacter_cancerogenus
s__Arthrospira_unclassified
s__Haemophilus_sputorum
s__Lactobacillus_casei_paracasei
s__Bacteroides_coprophilus
s__Collinsella_intestinalis
s__Scardovia_unclassified
s__Scardovia_wiggsiae
s__Lactobacillus_gasseri
s__Porphyromonas_bennonis
s__Roseolovirus_unclassified
s__Prevotella_timonensis
s__Eubacterium_brachy
s__Campylobacter_concisus
s__Acinetobacter_ursingii
s__Lactobacillus_phage_PL_1
s__Pediococcus_acidilactici
s__Pediococcus_lolii
s__Odoribacter_laneus
s__Butyricimonas_synergistica
s__Streptococcus_anginosus
s__Aeromonas_hydrophila
s__Aeromonas_unclassified
s__Fusobacterium_gonidiaformans
s__Lactobacillus_vaginalis
s__Lactobacillus_ruminis
s__Streptococcus_mutans
s__Coprobacillus_sp_D6
s__Parabacteroides_sp_D13
s__Bacteroides_sp_3_1_19
s__Phascolarctobacterium_succinatutens
s__Bifidobacterium_angulatum
s__Shigella_sonnei
s__Lactobacillus_reuteri
s__Haemophilus_haemolyticus
s__Clostridium_celatum
s__Gardnerella_vaginalis
s__Cronobacter_sakazakii
s__Actinomyces_urogenitalis
s__Actinomyces_graevenitzii
s__Catenibacterium_mitsuokai
s__Butyrivibrio_crossotus
s__Actinomyces_turicensis
s__Peptoniphilus_duerdenii
s__Campylobacter_curvus
s__Campylobacter_gracilis
s__Clostridium_methylpentosum
s__Enterococcus_phage_phiEf11
s__Propionibacterium_phage_P14_4
s__Enterococcus_avium
s__Enterococcus_casseliflavus
s__Weissella_unclassified
s__Lactobacillus_rhamnosus
s__Enterobacteria_phage_HK97
s__Abiotrophia_defectiva
s__Gemella_haemolysans
s__Streptococcus_cristatus
s__Staphylococcus_hominis
s__Pseudomonas_mendocina
s__Streptococcus_infantarius
s__Clostridium_sporogenes
s__Dasheen_mosaic_virus
s__Campylobacter_upsaliensis
s__Lachnospiraceae_bacterium_2_1_46FAA
s__Staphylococcus_phage_3A
s__Enterococcus_gallinarum
s__Varibaculum_cambriense
s__Propionibacterium_phage_P100_A
s__Coriobacteriaceae_bacterium_phI
s__Lactobacillus_johnsonii
s__Lactococcus_phage_bIL67
s__Rothia_unclassified
s__Proteus_penneri
s__Leuconostoc_unclassified
s__PhiCD119likevirus_unclassified
s__Alloprevotella_tannerae
s__Haemophilus_paraphrohaemolyticus
s__Lactobacillus_oris
s__Lactobacillus_crispatus
s__Rothia_dentocariosa
s__Anaerococcus_vaginalis
s__Eubacterium_limosum
s__Clostridium_hylemonae
s__Bartonella_unclassified
s__Anaerococcus_obesiensis
s__Gemella_morbillorum
s__Porphyromonas_endodontalis
s__Chicken_anemia_virus
s__Granulicatella_elegans
s__Alloprevotella_rava
s__Enterobacter_sp_MGH_8
s__Streptococcus_macedonicus
s__Streptococcus_gallolyticus
s__Cronobacter_malonaticus
s__Pediococcus_unclassified
s__Clostridium_butyricum
s__Prevotella_oralis
s__Neisseria_flavescens
s__Neisseria_subflava
s__Neisseria_meningitidis
s__Propionibacterium_phage_P100D
s__Campylobacter_showae
s__Atopobium_vaginae
s__Enterococcus_raffinosus
s__Acidaminococcus_sp_BV3L6
s__Enterobacteria_phage_RB14
s__Klebsiella_phage_KP15
s__Klebsiella_phage_KP27
s__Enterobacteria_phage_WA13_sensu_lato
s__Lactobacillus_jensenii
s__Prevotella_amnii
s__Klebsiella_sp_MS_92_3
s__Enterobacter_hormaechei
s__Bacteroidetes_bacterium_oral_taxon_272
s__Lautropia_mirabilis
s__Haemophilus_phage_HP1
s__Prevotella_bergensis
s__Jonquetella_anthropi
s__Campylobacter_hominis
s__P22likevirus_unclassified
s__Chlorobium_phaeobacteroides
s__Ruminococcus_champanellensis
s__Fusobacterium_mortiferum
s__Streptococcus_dysgalactiae
s__Pediococcus_pentosaceus
s__Actinomyces_odontolyticus
s__Corynebacterium_amycolatum
s__Providencia_rettgeri
s__Lactobacillus_plantarum
s__Lactobacillus_mucosae
s__Finegoldia_magna
s__Cellulosilyticum_lentocellum
s__Providencia_alcalifaciens
s__Leifsonia_unclassified
s__Lactobacillus_curvatus
s__Escherichia_sp_TW09276
s__Fretibacterium_fastidiosum
s__Treponema_lecithinolyticum
s__Enterobacteria_phage_JL1
s__Shigella_phage_EP23
s__Clostridium_spiroforme
s__Bacteroides_fluxus
s__Streptococcus_peroris
s__Peptoniphilus_lacrimalis
s__Enterocytozoon_bieneusi
s__Clostridiales_bacterium_BV3C26
s__Campylobacter_ureolyticus
s__Comamonas_unclassified
s__Enterobacter_mori
s__Wohlfahrtiimonas_chitiniclastica
s__Yersinia_enterocolitica
s__Brachyspira_pilosicoli
s__Brachyspira_unclassified
s__Acidaminococcus_fermentans
s__Enterobacteria_phage_HK630
s__Bacteroides_pectinophilus
s__Clostridium_sp_D5
s__Propionibacterium_phage_PAS50
s__Corynebacterium_kroppenstedtii
s__Mouse_mammary_tumor_virus
s__Propionibacterium_phage_P101A
s__Atopobium_rimae
s__Brevibacterium_unclassified
s__Atopobium_parvulum
s__Slackia_unclassified
s__Prevotella_oulorum
s__Actinomyces_europaeus
s__Ureaplasma_unclassified
s__Facklamia_hominis
s__Corynebacterium_accolens
s__Bacteroides_barnesiae
s__Acidaminococcus_sp_HPA0509
s__Marvinbryantia_formatexigens
s__Eubacterium_cylindroides
s__Mitsuokella_multacida
s__Synergistes_sp_3_1_syn1
s__Anaerococcus_lactolyticus
s__Serratia_marcescens
s__Staphylococcus_aureus
s__Lactobacillus_animalis
s__Enterobacteria_phage_mEpX2
s__Propionibacterium_phage_P104A
s__Torque_teno_virus
s__Rahnella_aquatilis
s__Lactococcus_garvieae
s__Enterobacteria_phage_SfV
s__Aerococcus_viridans
s__Leuconostoc_gelidum
s__Dialister_succinatiphilus
s__Propionibacterium_phage_PHL112N00
s__Pantoea_ananatis
s__Pseudomonas_fragi
s__Megasphaera_elsdenii
s__Olsenella_unclassified
s__Actinobaculum_schaalii
s__Haemophilus_influenzae
s__Bacteroides_sp_1_1_30
s__Bacteroidetes_oral_taxon_274
s__Prevotella_intermedia
s__Streptococcus_tigurinus
s__Enterococcus_durans
s__Bifidobacterium_asteroides
s__Tetragenococcus_halophilus
s__Prevotella_histicola
s__Prevotella_pallens
s__Human_adenovirus_E
s__Human_adenovirus_B
s__Clostridium_phytofermentans
s__Bacillus_sp_AP8
s__Yersinia_unclassified
s__Gemella_sanguinis
s__Enterococcus_mundtii
s__Enterococcus_asini
s__Enterococcus_dispar
"""

def fileDataToString(fileData):
    # "data:text/plain;base64,Y29udm94IHJhY2sgcGFyYW1zIHNldCBJbnN0YW5jZUJvb3RDb21tYW5kPSIvZXRjL2luaXQuZC9kb2NrZXIgc3RvcDsgZG1zZXR1cCByZW1vdmVfYWxsOyB2Z3JlbW92ZSAtLWZvcmNlIGRvY2tlcjsgbWtmcyAtdCBleHQ0IC1MIGRvY2tlciAtaSA0MDk2IC1GIC9kZXYveHZkY3o7IHJtIC1mciAvdmFyL2xpYi9kb2NrZXIvKjsgbWtkaXIgL3Zhci9saWIvZG9ja2VyL292ZXJsYXkyOyBtb3VudCAvZGV2L3h2ZGN6IC92YXIvbGliL2RvY2tlci9vdmVybGF5MjsgZWNobyAnRE9DS0VSX1NUT1JBR0VfT1BUSU9OUz1cIi0tc3RvcmFnZS1kcml2ZXI9b3ZlcmxheTJcIicgPiAvZXRjL3N5c2NvbmZpZy9kb2NrZXItc3RvcmFnZTsgZ3JlcCAtdiBkbVwuYmFzZXNpemUgL2V0Yy9zeXNjb25maWcvZG9ja2VyID4gL2V0Yy9zeXNjb25maWcvZG9ja2VyLXRtcDsgbXYgLWYgL2V0Yy9zeXNjb25maWcvZG9ja2VyLXRtcCAvZXRjL3N5c2NvbmZpZy9kb2NrZXI7IC9ldGMvaW5pdC5kL2RvY2tlciBzdGFydDsgcm0gLXJmIC92YXIvbGliL2Vjcy9kYXRhLyogL3Zhci9jYWNoZS9lY3MvKjsgc3RhcnQgZWNzIgo="
    try:
        return base64.b64decode(fileData.split('base64,')[1]).decode('utf-8')
    except:
        return defaultFileData


def predict(surveyResult):
    """
    This function responds to a request for /api/people/{lname}
    with one matching person from people

    :param lname:   last name of person to find
    :return:        person matching last name
    """

    # Bad input?
    badInput = False
    if badInput:
        abort(500, 'Invalid input data: %s', surveyResult)

    logging.info(surveyResult)
    inRemission, sesCdScore = predictIBDValues(surveyResult.get('microbiomeData'))

    return {
        'inRemission': inRemission,
        'sesCdScore': sesCdScore,
        'sourceSurveyResult': surveyResult
    }


#=========================================================================
# API Methods
#=========================================================================

def ping():

    return {
        'result': 'ping',
        'datetime': datetime.datetime.utcnow()
    }



def predictRemissionValue(microbiomeData):

    try:
        with open('pickle.classifier.remission.bin', mode='rb') as modelFile:
            modelContents = pickle.load(modelFile)
            flareupPrediction = ibd_predictor.predict(
                pickle_load=modelContents,
                data=metaflanVector,
                user=fileDataToString(microbiomeData),
            )
        # We return whether we are in remission - so inverse
        return False if flareupPrediction else True
    except:
        return True

def predictSesCdValue(microbiomeData):

    try:
        with open('pickle.regression.ses-cd.bin', mode='rb') as modelFile:
            modelContents = pickle.load(modelFile)
            prediction = ibd_predictor.predict(
                pickle_load=modelContents,
                data=metaflanVector,
                user=fileDataToString(microbiomeData),
            )
        return round(prediction)
    except:
        return 0

def predictIBDValues(microbiomeData):

    return predictRemissionValue(microbiomeData), predictSesCdValue(microbiomeData)