swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: DataHack 2018 - IBD Hack
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /ibd_remission/predict:
    post:
      operationId: ibd_remission.predict
      summary: Predicts whether an IBD patient has a disease in remission or not.
      parameters:
        - name: surveyResult
          in: body
          description: Survey result
          required: True
          schema:
            type: object
      responses:
        200:
          description: Successfully returned prediction
          schema:
            type: object
            properties:
              inRemission:
                type: boolean
              sourceSurveyResult:
                type: object
