swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: DataHack 2018 - IBD Hack
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:

  /ibd_remission/ping:

    get:
      operationId: ibd_remission.ping
      summary: Gets a ping response.
      description: |
        Gets a ping response. The response is a JSON object that contains the server time.
      # no security required here
      security: []
      responses:
        '200':
          description: Ping reponse.
          schema:
            type: object
            properties:
              result:
                type: string
              datetime:
                type: string
                format: date-time

  /ibd_remission/predict:
    post:
      operationId: ibd_remission.predict
      summary: Predicts whether an IBD patient has a disease in remission or not.
      parameters:
        - name: surveyResult
          in: body
          description: Survey result
          required: True
          schema:
            type: object
      responses:
        200:
          description: Successfully returned prediction
          schema:
            type: object
            properties:
              inRemission:
                type: boolean
              sourceSurveyResult:
                type: object
